[build]
  command = "pnpm install --no-frozen-lockfile && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--prefer-offline"
  PNPM_HOME = "/opt/buildhome/.pnpm"

[[plugins]]
  package = "@netlify/plugin-local-install"
